# Generated by Django 6.0.7 on 2026-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='promo_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Workshop', 'Workshop'), ('Music', 'Music'), ('Sports', 'Sports'), ('Education', 'Education'), ('AI', 'AI'), ('Startup', 'Startup'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Food', 'Food'), ('Design', 'Design'), ('Networking', 'Networking'), ('Finance', 'Finance')], max_length=100),
        ),
    ]
